# Generated by Django 5.1.15 on 2026-03-24 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('whatsapp_phone', models.CharField(help_text='Formato internacional, ej: +5491155551234', max_length=20, verbose_name='Teléfono WhatsApp')),
                ('last_period_start', models.DateField(blank=True, null=True, verbose_name='Último inicio de período')),
                ('cycle_length', models.PositiveSmallIntegerField(default=28, verbose_name='Duración del ciclo (días)')),
                ('next_predicted_period', models.DateField(blank=True, null=True, verbose_name='Próximo período estimado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de ciclo',
                'verbose_name_plural': 'Perfiles de ciclo',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('scheduled_for', models.DateField(verbose_name='Programado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado a las')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=10, verbose_name='Estado')),
                ('provider_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta del proveedor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cycles.cycleprofile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Log de notificación',
                'verbose_name_plural': 'Logs de notificación',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'scheduled_for'), name='unique_notification_per_profile_date')],
            },
        ),
        migrations.CreateModel(
            name='PeriodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_records', to='cycles.cycleprofile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Registro de período',
                'verbose_name_plural': 'Registros de período',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'start_date'), name='unique_period_per_profile_date')],
            },
        ),
    ]
